spring:
  application:
    name: yu-ai-code-mother-backend
  # mysql
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://47.117.37.167:23306/yu_ai_code_mother
#    username: root
#    password: root
#hikari:
#  maximum-pool-size: 10
#  minimum-idle: 2
#  max-lifetime: 28000_000   # 7 小时 46 分钟，比 8 小时少 1 分钟左右
#  idle-timeout: 600000      # 10 分钟
#  keepalive-time: 300000    # 5 分钟
#  validation-timeout: 5000  # 5 秒
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.159.102:3306/yu_ai_code_mother
    username: root
    password: root
  profiles:
    active: local
  lifecycle:
    timeout-per-shutdown-phase: 120s
server:
  port: 8123
  servlet:
    context-path: /api

# springdoc-openapi
# http://localhost:8123/api/doc.html 接口文档地址
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.lynn.yuaicodemother.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn