spring:
  application:
    name: yu-ai-code-mother-backend
server:
  port: 8123
  servlet:
    context-path: /api

# springdoc-openapi
# http://localhost:8123/api/doc.html 接口文档地址
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.lynn.yuaicodemother.controller
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn